spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/springbatch
    username: rubok
    password: 213216

logging:
  level:
    root: info